apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app.kubernetes.io/name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: node-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-app
    spec:
      containers:
      - image: docker.io/gauravpachahara/nodeapp:$IMAGE_TAG
        name: nodeapp
        ports:
            - containerPort: 8080
        
               
